-- Seed data for initial testing

-- 1) Test user
--    Using a bcrypt-hash for "test.password" below.
--    Hash generated by e.g. bcrypt cost=10.
--    (Of course, in a real environment you'd want to manage secrets more carefully!)
INSERT INTO users (id, username, email, password_hash)
VALUES
    (1, 'test.user', 'test.user@example.com', '$2a$10$U9TcJgB4JZrEE61hh4E2dOIQhrkZpZ73vaT/6Gth2zSa0jk2bWCS.');

-- 2) Budgets
--    Assign budget limits for the default categories inserted in 000002_create_categories_table.up.sql
INSERT INTO budgets (user_id, category_id, limit_amount)
VALUES
    (1, 1, 300.00),  -- Groceries
    (1, 2, 1000.00), -- Rent
    (1, 3, 200.00);  -- Entertainment

-- 3) Transactions
--    Simple examples of debit and credit transactions.
INSERT INTO transactions (user_id, amount, transaction_type, category_id)
VALUES
    (1, 50.00,  'debit', 1),  -- Groceries
    (1, 500.00, 'debit', 2),  -- Rent
    (1, 20.00,  'debit', 3),  -- Entertainment
    (1, 2000.00, 'credit', NULL); -- A credit (no category)

-- 4) AI Predictions
--    Placeholder data showing how an AI tool might have predicted category/amount
INSERT INTO ai_predictions (user_id, predicted_category, predicted_amount)
VALUES
    (1, 'Groceries', 45.00),
    (1, 'Rent', 550.00),
    (1, 'Entertainment', 30.00);
